### ISSUE TITLE
Add support for Node 17 and 18. Drop support for Node 10, 12 and 15.

### ISSUE THREAD

**Issue by nolanmar511** [google/pprof-nodejs#170]
Node 17 will be released on 6/1. Support for Node 15 will end on that day.

We should add tests and pre-built binarys for Node 17, and remove tests and prebuilt binaries for Node 15 then.

**Comment by amchiclet** [comment]
Revisiting this issue now. Updating the title so it matches the current [releases](https://nodejs.org/en/about/releases/) of node.

The plan is to update the tests for node 17 and 18 and drop tests for node 10 and 15.

Would also like to note that since we use `source-map`, the tests for node 18 will fail until the upstream [issue](https://github.com/mozilla/source-map/issues/454) is officially fixed.

**Comment by nolanmar511** [comment]
`node-pre-gyp` does not currently have maintainers (https://github.com/mapbox/node-pre-gyp/issues/657) and does not support building node 18 binaries on a machine using another version of node (https://github.com/mapbox/node-pre-gyp/issues/647).

Given this, the approach for generating pre-built binaries will need to change to build binaries for Node 18.

**Comment by nolanmar511** [comment]
Might be possible to switch to using Node.js's [inspector](https://nodejs.org/api/inspector.html) & drop the native portion of this library once LTS for Node 12 has ended.

**Comment by aabmass** [comment]
Should also update the docs here https://cloud.google.com/profiler/docs/profiling-nodejs

**Comment by aabmass** [comment]
This library works fine on node 18 already. The only issue is we can't supply pre-built binaries. Are you seeing a specific issue @pietrodn ?

**Comment by pietrodn** [comment]
Sorry, I realized that somehow the binary I had in `node_modules` was built against the wrong Node runtime. A reinstall did the trick.

**Comment by ericwooley** [comment]
Should this not have 20 as well now?

**Comment by franleplant** [comment]
would love to see support for node@20 `20`

**Comment by aabmass** [comment]
It should work fine in node 20 already. Please see https://github.com/google/pprof-nodejs/issues/273#issuecomment-1918427012, for more info.

**Comment by aabmass** [comment]
I'm going to close this as fixed since we support up to Node 20. The only part of this issue still missing is the pre-built binaries, which I will open a separate issue for.
